### ISSUE TITLE
Query results saved with wrong resolution

### ISSUE THREAD

**Issue by z0u** [vpac-innovations/rsa#24]
Cell resolution for query _stats_ results [is hard-coded](https://github.com/vpac-innovations/rsa/blob/d1291af787ffb4dab312692c576b6d4af38681ce/src/rsaworkers/src/main/java/org/vpac/worker/Master.java#L259) to 25m. This means the area displayed in the UI is wrong.

When Spatial Cube Services splits up the work into tiles, [it knows what resolution it is](https://github.com/vpac-innovations/rsa/blob/d1291af787ffb4dab312692c576b6d4af38681ce/src/spatialcubeservice/src/main/java/org/vpac/web/controller/DataController.java#L811). The resolution should probably be included in the Work object, and used when saving the data to the database.

**Comment by forjin-vpac-innovations** [comment]
Fixed 47661afedd751db8bbf81370cf942832b4624ba8
