### ISSUE TITLE
Query progress should have better precision

### ISSUE THREAD

**Issue by z0u** [vpac-innovations/rsa#27]
When running a query, we only see progress in chunks of tiles (e.g. 25%, 50%, 75%, 100% for 4 tiles). The query engine can report much more often than this; this information should be used to report on progress through fractions of tiles.

**Comment by z0u** [comment]
The class that needs to do this is `org.vpac.worker.WorkProgress`. When its `addProcessedQuanta` method is called, we can send a message to `Master` with the new fraction. `Master` can then send a message to the `DatabaseActor` with accumulated fractions to update the `JobProgress`.

Some suggestions (feel free to disagree):
- Change the `WorkProgress` constructor to take an `ActorRef` for the master.
- `WorkProgress` should only send a message to `Master` if the fraction has changed significantly since the last time, e.g. if the new fraction is `0.05` (5%), only send a message to `Master` if the last message was sent when the fraction was `0.03` (3%).
- `Master` should only send a message to `DatabaseActor` when the combined fraction has changed significantly, so that when processing 100s of tiles we don't write to the database 100s of times every second.

**Comment by forjin-vpac-innovations** [comment]
Completed db129544d3ce20034e21bcb67e095eb026f3e52f
