### ISSUE TITLE
gdalconst error

### ISSUE THREAD

**Issue by forjin-vpac-innovations** [vpac-innovations/rsa#32]
Hi,

I am currently working on dockerize rsa. 
During this task, I need to install rsa once again. But there is an error which is very familiar to me during installation .
Here is the error message.

> Caused by: java.lang.NoClassDefFoundError: org/gdal/gdalconst/gdalconstConstants
>         at org.vpac.ndg.rasterdetails.RasterDetails.<clinit>(RasterDetails.java:31)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:606)
>         at java.lang.Class.getEnumConstantsShared(Class.java:3085)
>         at java.lang.System$2.getEnumConstantsShared(System.java:1189)
>         at java.util.EnumMap.getKeyUniverse(EnumMap.java:750)
>         at java.util.EnumMap.<init>(EnumMap.java:137)
>         at com.sun.xml.bind.v2.model.impl.RuntimeEnumLeafInfoImpl.<init>(RuntimeEnumLeafInfoImpl.java:47)
>         at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.createEnumLeafInfo(RuntimeModelBuilder.java:65)
>         at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.createEnumLeafInfo(RuntimeModelBuilder.java:42)
>         at com.sun.xml.bind.v2.model.impl.ModelBuilder.getClassInfo(ModelBuilder.java:170)
>         at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:60)
>         at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:42)
>         at com.sun.xml.bind.v2.model.impl.ModelBuilder.getClassInfo(ModelBuilder.java:155)
>         at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:55)
>         at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:42)
>         at com.sun.xml.bind.v2.model.impl.ModelBuilder.getTypeInfo(ModelBuilder.java:261)
>         at com.sun.xml.bind.v2.model.impl.SingleTypePropertyInfoImpl.getTarget(SingleTypePropertyInfoImpl.java:54)
>         at com.sun.xml.bind.v2.model.impl.RuntimeAttributePropertyInfoImpl.getTarget(RuntimeAttributePropertyInfoImpl.java:26)
>         at com.sun.xml.bind.v2.model.impl.RuntimeAttributePropertyInfoImpl.getTarget(RuntimeAttributePropertyInfoImpl.java:14)
>         at com.sun.xml.bind.v2.model.impl.SingleTypePropertyInfoImpl.ref(SingleTypePropertyInfoImpl.java:48)
>         at com.sun.xml.bind.v2.model.impl.RuntimeAttributePropertyInfoImpl.ref(RuntimeAttributePropertyInfoImpl.java:30)
>         at com.sun.xml.bind.v2.model.impl.RuntimeAttributePropertyInfoImpl.ref(RuntimeAttributePropertyInfoImpl.java:14)
>         at com.sun.xml.bind.v2.model.impl.ModelBuilder.getClassInfo(ModelBuilder.java:201)
>         at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:60)
>         at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:42)
>         at com.sun.xml.bind.v2.model.impl.ModelBuilder.getClassInfo(ModelBuilder.java:155)
>         at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:55)
>         at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:42)
>         at com.sun.xml.bind.v2.model.impl.ModelBuilder.getTypeInfo(ModelBuilder.java:261)
>         at com.sun.xml.bind.v2.model.impl.ModelBuilder.getTypeInfo(ModelBuilder.java:276)
>         at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:399)
>         at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:253)
>         at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:84)
>         at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:66)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:606)
>         at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:248)
>         at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:235)
>         at javax.xml.bind.ContextFinder.find(ContextFinder.java:432)
>         at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:637)
>         at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:584)
>         at org.springframework.oxm.jaxb.Jaxb2Marshaller.createJaxbContextFromClasses(Jaxb2Marshaller.java:443)
>         at org.springframework.oxm.jaxb.Jaxb2Marshaller.getJaxbContext(Jaxb2Marshaller.java:399)
>         at org.springframework.oxm.jaxb.Jaxb2Marshaller.afterPropertiesSet(Jaxb2Marshaller.java:385)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1514)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1452)
>         ... 52 more
> Caused by: java.lang.ClassNotFoundException: org.gdal.gdalconst.gdalconstConstants
>         at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1680)
>         at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1526)

Please let me know if you know about this error. I was just following [Manual Installation](https://github.com/vpac-innovations/rsa/blob/master/doc/manual_install.md).

**Comment by z0u** [comment]
On my machine, I just use Ubuntu 14.04's stock GDAL.

``` bash
apt-get install gdal-bin libgdal-dev libgdal-java 
```

Try that. It turns out I'm using a custom build of `libnetcdf`, but I don't think you need it - try without building it.

**Comment by z0u** [comment]
Also, you might need to specify the path to the native library for `gdal.jar`. Try editing Tomcat's `setenv.sh`, and add:

``` bash
JAVA_OPTS=-Djava.library.path="/usr/lib/jni"
```

Note that the `.jar` file is `/usr/share/java/gdal.jar` while the `.so` file is `/usr/lib/jni/libgdaljni.so`.

**Comment by forjin-vpac-innovations** [comment]
I solve this problem linking goal.jar to web lib

``` bash
ln -s /usr/share/java/gdal.jar /usr/share/tomcat6/lib/
```

But still has an error because there is database connection using user `rsa`

Thanks

**Comment by z0u** [comment]
> I solve this problem linking goal.jar to web lib

OK. Did you try editing `/etc/tomcat6/catalina.properties`? Maybe if you add the location of the jar file to `server.loader` in that file it would work. But, a symlink sounds OK too.

**Comment by z0u** [comment]
Reference for previous comment: http://stackoverflow.com/a/1863646/320036
