### ISSUE TITLE
Docker container gets same ip again then rsa cannot auto recover from failure

### ISSUE THREAD

**Issue by forjin-vpac-innovations** [vpac-innovations/rsa#38]
I found a new issue when rsa container get same ip address as previous rsa, then the cluster couldn't distinguish it's recovered or new machine is invoked.

Need to find way to get new ip address every time, it fails.

**Comment by z0u** [comment]
How do you reproduce this? `docker restart <container>`?

**Comment by forjin-vpac-innovations** [comment]
I started r1 as rsa(master & worker), and then started web.

And after a minute, I started r2, and check log whether it successfully connected to r1, and remove r1 then r2 will take over master(secondary master). 

And started another rsa in docker named r3, then it's got same address as r1 because in the subnet the ip address is empty.

```
1. r1 started
2. web started
3. r2 started.
4. r1 removed.
5. r3 started. <-- break cluster
```

Then all cluster is broken.

**Comment by z0u** [comment]
OK. Please also test what happens when a container restarts.

**Comment by forjin-vpac-innovations** [comment]
I tested restarting docker, it's same as shutdown and restart docker.

```
1. r1 started.
2. web started.
3. r2 started.
4. r1 restarted.
```

It's successfully replaced master.

**Comment by forjin-vpac-innovations** [comment]
If I restart r2 then it break again.

```
5. r2 restarted <-- break cluster
```

**Comment by z0u** [comment]
Cool, thanks for testing. What if `web` is restarted?

**Comment by forjin-vpac-innovations** [comment]
@z0u What point? number 6?

**Comment by forjin-vpac-innovations** [comment]
Em... Sometimes even if r2 is restarted the cluster doesn't break. Strange.

**Comment by z0u** [comment]
> What point?

When the cluster is running properly. For example:

```
1. r1 started
2. web started
3. r2 started.
4. web restarted. <-- ???
```

I guess we should test like this:

```
1. r1 started
2. web started
3. r2 started.
-> Check that cluster is working
4. r1 restarted.
-> Check that cluster is working
5. web restarted.
-> Check that cluster is working
6. r2 restarted.
-> Check that cluster is working
7. r1, web, r2 restarted all at the same time.
-> Check that cluster is working
```

**Comment by z0u** [comment]
> Em... Sometimes [...]

It would be good to have [that sequence](#issuecomment-173021976) in a test _script_ so we can run it 10 times in a row and make sure it doesn't break.

**Comment by forjin-vpac-innovations** [comment]
```
1. r1 started
2. web started
3. r2 started.
4. web restarted. <-- ???
```

For this test working fine. Tested two times but no problem.

**Comment by forjin-vpac-innovations** [comment]
```
1. r1 started
2. web started
3. r2 started.
-> Check that cluster is working : No problem 100%
4. r1 restarted.
-> Check that cluster is working : No problem for test1
5. web restarted.
-> Check that cluster is working : No problem for test1
6. r2 restarted.
-> Check that cluster is working : No problem for test1
7. r1, web, r2 restarted all at the same time.
-> Check that cluster is working : Break for test1
```

**Comment by forjin-vpac-innovations** [comment]
If I test one by one and wait until all tasks are finished, there is no problem.
Even another docker has same ip address or not.

**Comment by forjin-vpac-innovations** [comment]
If I test docker creation and deletion and recreation very fast, it happens(broke) again.

**Comment by z0u** [comment]
> wait until all tasks are finished

What is a "task"? A query, or the bootstrap procedure? ... ideally it should be able to recover no matter when it is restarted

**Comment by forjin-vpac-innovations** [comment]
The  "all tasks" means bootstrap procedure.

It's true, the system should be recovered automatically.

**Comment by forjin-vpac-innovations** [comment]
I think this issue is finished.
