### ISSUE TITLE
Set up networked file system for storage pool on AWS

### ISSUE THREAD

**Issue by z0u** [vpac-innovations/rsa#42]
Until we upgrade RSA to store tiles in an object store (S3), we need a place to store files on the cloud. Options:
1. Gluster - GPL3
2. Softnas - 3rd-party proprietary
3. EFS - Amazon proprietary, not available in Sydney yet

Let's go with Gluster, until EFS becomes available. Then we can re-evaluate.

**Comment by forjin-vpac-innovations** [comment]
We need to decide.
1. What type of instance is proper? e.g. t2.small
2. What size of disk?
3. Whick EBS Volume type?
   http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html

I think No2 answer is 500G.

**Comment by z0u** [comment]
SO we need something like 500GB of storage. We need to:
- Choose EC2 instances that are beefy enough to handle the IO that RSA wants to do.
- Probably more than one EC2 instance for a single gluster system? The install guide says ["Deploy at least two instances."](http://gluster.readthedocs.org/en/latest/Install-Guide/Setup_aws/)
- When starting an instance, it's probably good to keep the drives separate:
  - 5GB or so for the operating system (/dev/sda?)
  - Bigger drive for gluster storage (/dev/sdb?)

Question: Is it like RAID? If so, should we choose replication or striping? Would two machines with 250GB of storage give us 250GB or fast storage, or 500GB of slower storage?

**Comment by z0u** [comment]
This is not a public topic; migrating to other GitHub account.
