### ISSUE TITLE
Calculate cost of hosting on AWS

### ISSUE THREAD

**Issue by z0u** [vpac-innovations/rsa#43]
Use AWS' [simple calculator](http://calculator.s3.amazonaws.com/index.html) to estimate a hosting cost for our SLIM deployment.
- EC2 nodes
  - RSA Web (1), workers (1+, scalable), Landblade (1)
  - Gluster servers (2+?) See #42 
- RDS instances
- Remember to account for EBS volumes (storage pool, RDS)
- Network IO (just guess)

Remeber to set it to Sydney and disable the free tier to get realistic prices. Then, press the _Save and share_ button (see below) and post the URL and summary here.

![image](https://cloud.githubusercontent.com/assets/1408875/12632415/da4819b6-c5ab-11e5-896c-29d99509ded2.png)

**Comment by forjin-vpac-innovations** [comment]
Currently $130
<img width="1795" alt="screen shot 2016-01-28 at 10 50 09 am" src="https://cloud.githubusercontent.com/assets/5170941/12632568/1a45f064-c5ad-11e5-86eb-2abaa1643c4a.png">

**Comment by z0u** [comment]
Thanks. Please post a URL so we can see the details. Actually we don't need the screenshot.

**Comment by z0u** [comment]
actually we should move this discussion to our other github account.
