### ISSUE TITLE
Regression bug: nodata treated incorrectly when generating map tile for mask queries

### ISSUE THREAD

**Issue by lachlanhurst** [vpac-innovations/rsa#51]
Believe this is related to the fix we implemented to get the colours between LB and RSA tiles for categorical query results. Just ran a query and it seems our nodata treatment is off a bit, same color used for nodata and 'did not match query'.
http://dev.landblade.vpac-innovations.com.au/#/query/57712c1a3205a70001e17637
![image](https://cloud.githubusercontent.com/assets/4476041/16381730/452118be-3cc1-11e6-92b4-768b7d66c613.jpeg)

**Comment by forjin-vpac-innovations** [comment]
Yes it was fixed. I think its not merged perfectly for the your current working branch.

Let me check.

**Comment by forjin-vpac-innovations** [comment]
fixed in fbaa9161188e72d8aa377ad09c5ad4e3c7cd395d
